global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'document-control'
    static_configs:
      - targets: ['document-control:3000']
    metrics_path: '/metrics'
